import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyToVaults } from "./copy-to-vault.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: 'watch-deploy',
			setup(build) {
				build.onEnd(result => {
					if (result.errors.length === 0) {
						console.log('Build successful, deploying to vaults...');
						copyToVaults();
					}
				});
			},
		},
	],
});

// Add output for styles.css
if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
 