title: Make It Rain Documentation
description: Documentation for the 'Make It Rain' Obsidian plugin
baseurl: /make-it-rain
url: https://frostmute.github.io
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-hacker
